# Generated by Django 3.2.7 on 2021-09-11 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sideinfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footersideinfo',
            name='fb_link',
        ),
        migrations.AddField(
            model_name='footersideinfo',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='footersideinfo',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='footersideinfo',
            name='instagram_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='footersideinfo',
            name='twitter_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='footersideinfo',
            name='youtube_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='headersideinfo',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='footersideinfo',
            name='copyrightmsg',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
