# Generated by Django 3.2.7 on 2021-09-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sideinfo', '0002_auto_20210911_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footersideinfo',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='headersideinfo',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
