# Generated by Django 3.2.7 on 2021-09-12 04:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sideinfo', '0005_headersideinfo_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headersideinfo',
            name='address',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
